Add test cases for the ansible_managed header.
linux-system-roles/metrics pull request #109
Opened 2022-02-24 22:37 UTC by nhosoi

Files to be checked:
  - /var/lib/pcp/pmdas/bpftrace/bpftrace.conf
  - /var/lib/pcp/pmdas/elasticsearch/elasticsearch.conf
  - /etc/grafana/grafana.ini
  - /usr/lib/systemd/system/pcp2elasticsearch.service
  - /var/lib/pcp/pmdas/mssql/mssql.conf
  - /etc/sysconfig/pmlogger
  - /etc/sysconfig/pmlogger_timers
  - /etc/sysconfig/pmproxy
  - /etc/pcp/pmie/control.d/<host>

2022-02-24 23:57 UTC, richm commented on tests/check_header.yml
> +- name: Get the ansible_managed header in bpfttace.conf
I think this should be `{{ __test_config_path }}` instead of `bpfttace.conf`

Also, the `grep` will fail if the pattern is not found - so do you need the `assert` task?

2022-02-24 23:58 UTC, richm commented
does this PR depend on some ansible-pcp change?

2022-02-25 00:16 UTC, nhosoi commented on tests/check_header.yml
> +- name: Get the ansible_managed header in bpfttace.conf
Indeed, the assert task is no use... Removing it. Thanks!

2022-02-25 00:20 UTC, nhosoi commented
> does this PR depend on some ansible-pcp change?

- If an exisiting sub-roles is deleted, the related test script would be also deleted together. So, I'd think it's safe.
- If a new sub-role is added, it won't be covered.
- If some configuration file path is changed, the test would fail with no such file or directory...

2022-02-25 00:35 UTC, nhosoi commented
Tests are failing in various platforms...  Changing to WIP...

2022-02-25 16:52 UTC, richm commented
looks like there is a bug - the ansible_managed header is not being added to the elasticsearch.conf

2022-02-25 19:04 UTC, nhosoi commented
> looks like there is a bug - the ansible_managed header is not being added to the elasticsearch.conf

@richm, yes, mssql.conf, as well.

On the failed platforms, the file is a symlink.
```
# ls -l /var/lib/pcp/pmdas/mssql/mssql.conf
lrwxrwxrwx. 1 root root 39 Feb 25 18:43 /var/lib/pcp/pmdas/mssql/mssql.conf -> ../../../../../etc/pcp/mssql/mssql.conf
# ls -l /etc/pcp/mssql/mssql.conf 
-rw-------. 1 root root 506 Feb  2 03:19 /etc/pcp/mssql/mssql.conf
```
And by default, the template module does not follow the symlink. If we add `follow: yes`, then the file is updated.
```
- name: Ensure PCP SQL Server agent is configured
  template:
    src: mssql.conf.j2
    dest: "{{ __mssql_conf }}"
    follow: yes
    mode: 0600
  when: mssql_metrics_provider == 'pcp'
```
I think the issue is being discussed on the gchat. :)

2022-02-25 19:07 UTC, richm commented
Is this https://bugzilla.redhat.com/show_bug.cgi?id=2058655 ?

2022-02-25 19:08 UTC, nhosoi commented
@richm, @natoscott, may I open a pr to add `follow: yes`? If so, should it be put just in mssql and elasticsearch, or should all the template tasks in ansible-pcp be updated, too?

2022-02-25 19:13 UTC, nhosoi commented
> Is this https://bugzilla.redhat.com/show_bug.cgi?id=2058655 ?

Yes, looks the same!

2022-02-26 00:02 UTC, nhosoi commented
Here's my observation.
Before running the task `Ensure PCP SQL Server agent is configured` (https://github.com/linux-system-roles/metrics/blob/main/vendor/github.com/performancecopilot/ansible-pcp/roles/mssql/tasks/main.yml#L33-L38), 
`/var/lib/pcp/pmdas/mssql/mssql.conf` is a symlink.
```
ls -l /var/lib/pcp/pmdas/mssql/mssql.conf
lrwxrwxrwx. 1 root root 39 Feb 25 22:53 /var/lib/pcp/pmdas/mssql/mssql.conf -> ../../../../../etc/pcp/mssql/mssql.conf
```
Just after the task `Ensure PCP SQL Server agent is configured`, it's turned to be an regular file and the ansible header is added.
```
[snippet of stat]
"path": "/var/lib/pcp/pmdas/mssql/mssql.conf"
"isreg": true
"islnk": false
[head of /var/lib/pcp/pmdas/mssql/mssql.conf]
"stdout": "#\n# Ansible managed\n#\n[connection]\n..."
```
On the succeeded platform (e.g., [rhel-guest-image-8.6-1364.x86_64.qcow2](http://download.hosts.prod.upshift.rdu2.redhat.com/rhel-8/nightly/RHEL-8/RHEL-8.6.0-20220224.2/compose/BaseOS/x86_64/images/rhel-guest-image-8.6-1364.x86_64.qcow2)), the two files `/var/lib/pcp/pmdas/mssql/mssql.conf` and `/etc/pcp/mssql/mssql.conf` are independent. The former has the ansible header; the latter does not.

On the failed platform (e.g., [Fedora-Cloud-Base-34-20220225.0.x86_64.qcow2](https://kojipkgs.fedoraproject.org/compose/cloud/latest-Fedora-Cloud-34/compose/Cloud/x86_64/images/Fedora-Cloud-Base-34-20220225.0.x86_64.qcow2), the two files `/var/lib/pcp/pmdas/mssql/mssql.conf` and `/etc/pcp/mssql/mssql.conf` are once separated in the same way as for rhel 8.6, but in the test checking code, they are back to the symlink and its target. And the ansible managed header is wiped out since it was not added to `/etc/pcp/mssql/mssql.conf`. Sadly, I could not figure out when and how `/var/lib/pcp/pmdas/mssql/mssql.conf` was back to a symlink.

According to https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html#parameter-follow, symbolic links will not be followed, by default. I guess we are seeing this behavior. And as the main(?) config file `/etc/pcp/mssql/mssql.conf` is not updated, the mssql agent is in an odd state. To fix it, I'd think we should set `follow: yes` to the template module in https://github.com/linux-system-roles/metrics/blob/main/vendor/github.com/performancecopilot/ansible-pcp/roles/mssql/tasks/main.yml#L33-L38.

2022-03-01 00:35 UTC, natoscott commented
> may I open a pr to add `follow: yes`? If so, should it be put just in mssql and elasticsearch, or should all the template tasks in ansible-pcp be updated, too?

@noriko yep, thanks for doing that.  Looking through these changes now.  I think the changes below vendor/ here in this PR should be dropped as a result, and perhaps we should even move your new test cases here over to ansible-pcp too?

2022-03-01 00:37 UTC, natoscott requested changes
As per earlier comment, should be no vendor/ file changes here and consider moving the tests to ansible-pcp too (since all the affected config file templates live there).

2022-03-01 02:39 UTC, nhosoi commented
@natoscott, thank your for merging https://github.com/performancecopilot/ansible-pcp/pull/32.

Once the pr is "vendor"ed, I'm going to update this pr and run some more tests. Thanks!

2022-03-01 05:10 UTC, natoscott commented
> Sadly, I could not figure out when and how `/var/lib/pcp/pmdas/mssql/mssql.conf` was back to a symlink.

@nhosoi there's two ways this can happen.

Firstly during a regular install / upgrade of the package, rpm will ensure the filesystem entry is in the symlink form.

The other way is via systemd where the tmpfiles.d functionality (re-)creates this.  This is controlled via the file  /usr/lib/tmpfiles.d/pcp-pmda-mssql.conf from the pcp-pmda-mssql rpm package.  This is dealing with issues around /var filesystem contents being transient, with some customers disallowing executable files on /var, and with backwards-compatibility with older versions of PCP where all sorts of permanent state was stored in /var files.

2022-03-01 20:04 UTC, nhosoi commented
Rebased with the main branch including the fix https://github.com/performancecopilot/ansible-pcp/pull/32 and squashed the multiple commits into one.

2022-03-14 16:04 UTC, nhosoi commented
@natoscott, could you please review this pr once again? Thanks!

2022-03-14 16:05 UTC, richm commented
[citest bad]

2022-03-14 21:09 UTC, natoscott approved these changes
Looks good to me @nhosoi

2022-03-14 21:10 UTC, merged