Use the firewall role and the selinux role from the metrics role
linux-system-roles/metrics pull request #126
Opened 2022-09-02 23:26 UTC by nhosoi

- Introduce metrics_manage_firewall to use the firewall role to
  manage the pmcd port, the pmproxy ports, the grafana port and
  the redis port depending upon the configuration parameters.
  metrics_manage_firewall is set to true, by default.

- Introduce metrics_manage_selinux to use the selinux role to
  manage the pmcd port, the pmproxy ports, the grafana port and
  the redis port depending upon the configuration parameters.
  If the variable is set to false, the selinux configuration is
  disabled.

- Add the test check task check_firewall_selinux.yml for verify
  the ports status.

- Add meta/collection-requirements.yml

2022-09-02 23:41 UTC, richm commented on tasks/firewall.yml
> +    _state_value: "{{ 'enabled' if metrics_manage_firewall | d() |
`"{{ metrics_manage_firewall | ternary('enabled', 'disabled') }}"`
I don't think you need the `d()` because it is always set

2022-09-02 23:44 UTC, richm commented on tasks/firewall.yml
> +        __metrics_firewall: "{{ __metrics_firewall |
I think you should use `__metrics_firewall | d([])` here and below
if `metrics_provider != 'pcp'`, will `__metrics_firewall` always be set?  It's possible it could be set to a previous value too since you are using `set_fact` it will be a global variable

2022-09-02 23:46 UTC, richm commented on tasks/firewall.yml
> +        - metrics_graph_service|d(false)|bool or
you shouldn't need the `d(false)` here or below because both `metrics_graph_service` and `metrics_query_service` are defined in defaults/main.yml and should always have a value

2022-09-02 23:49 UTC, richm commented on tasks/selinux.yml
> +    _state_value: "{{ 'on' if metrics_manage_selinux | d() |
`"{{ metrics_manage_selinux | ternary('on', 'off') }}"`

2022-09-02 23:50 UTC, richm commented on tests/check_firewall_selinux.yml
> +        - not (metrics_graph_service|d(false)|bool)
you can just use `not metrics_graph_service` here - and below

2022-09-02 23:50 UTC, nhosoi commented on tasks/firewall.yml
> +    _state_value: "{{ 'enabled' if metrics_manage_firewall | d() |
Thanks, @richm!
I copied & pasted the code from https://github.com/linux-system-roles/ha_cluster/pull/63. I'm fixing the counter part, too. :p

2022-09-02 23:54 UTC, richm commented on tests/check_firewall_selinux.yml
> +        - not (metrics_graph_service|d(false)|bool)
hm - I guess you do need the `d(..)` here - the issue here is that this is outside of the role scope, and so you don't have access to the defaults set in defaults/main.yml - you could also do 
```yaml
include_role:
  name: linux-system-roles.metrics
  public: true
```
to export all of the role variables from defaults/main.yml into the test playbook - however, I don't think it is a problem here, because you are only using a few boolean variables and their default values are well known

2022-09-02 23:57 UTC, nhosoi commented on tasks/firewall.yml
> +        __metrics_firewall: "{{ __metrics_firewall |
Hmmm, then instead, I guess I'd better initialize it like this?
```
@@ -1,6 +1,10 @@
 # SPDX-License-Identifier: MIT
 ---
 - block:
+    - name: Initialize __metrics_firewall
+      set_fact:
+        __metrics_firewall: []
+
     - name: Port for pmcd
       set_fact:
         __metrics_firewall:
```

2022-09-03 00:01 UTC, nhosoi commented on tasks/firewall.yml
> +        - metrics_graph_service|d(false)|bool or
I borrowed the condition, e.g., from here. :p
https://github.com/linux-system-roles/metrics/blob/main/tasks/main.yml#L81-L82
I could fix this line 16, but we don't want to touch the other places, right?

2022-09-06 22:16 UTC, natoscott requested changes
@nhosoi thanks for hacking on this!  Very comprehensive - you've found all the different ports, nicely done.  Few minor suggestions...

2022-09-06 22:16 UTC, natoscott commented on tasks/firewall.yml
> +        - metrics_graph_service|d(false)|bool or
@nhosoi perhaps a followup commit for the other places?  I don't recall any special reason for it being the way it is

2022-09-06 22:16 UTC, natoscott commented on tests/check_firewall_selinux.yml
> +        - "'44323/tcp' not in _result.stdout"
We can get rid of the port 44323 setting here (and everywhere else using it) - its a backwards-compatibility port for the original implementation of PCP REST API from a long-retired daemon.  Modern installations do not need this (grafana-pcp for example uses pmproxy via port 44322 for REST API services exclusively).

2022-09-06 22:16 UTC, natoscott commented on tests/check_firewall_selinux.yml
> +        - "'44323/tcp' in _result.stdout"
As above.

2022-09-06 22:16 UTC, natoscott commented on tests/check_firewall_selinux.yml
> +    - name: "Check firewall port status for pmlogger and pmproxy;
As above.

2022-09-06 22:16 UTC, natoscott commented on tests/check_firewall_selinux.yml
> +    - name: "Check firewall port status for pmlogger and pmproxy;
Drop "pmlogger and" here - these ports are related to pmproxy only.

2022-09-06 22:16 UTC, natoscott commented on README.md
> +Manage the pmcd port, the pmproxy ports, the grafana port and the redis
See details below, but no need to use "ports" plural here once those other changes are made.

2022-09-06 22:16 UTC, natoscott commented on README.md
> +Assign the pmcd port, the pmproxy ports, the grafana port and the redis
Ditto.

2022-09-06 22:16 UTC, natoscott commented on README.md
> +Manage the pmcd port, the pmproxy ports, the grafana port and the redis
Also, rest of this doc refers to "Grafana" and "Redis" (capitalised).

2022-09-07 00:15 UTC, nhosoi commented on tasks/firewall.yml
> +        - metrics_graph_service|d(false)|bool or
@natoscott, the value to be set to `pcp_rest_api` is the one I borrowed here. I thought this condition works for our purpose, too. Do you think d(false) is not needed in the following line 81 and 82?
```
 81     pcp_rest_api: "{{ metrics_query_service|d(false)|bool or
 82                       metrics_graph_service|d(false)|bool }}"
```

2022-09-07 00:18 UTC, nhosoi commented
Thank you for your reviews, @natoscott ! As you see in the CI section, we are not able to run the tests with the base os ci now due to the new functionalities we are adding. Hopefully, we can run them some time this week or a week after...

2022-09-08 02:54 UTC, natoscott commented on tasks/firewall.yml
> +        - metrics_graph_service|d(false)|bool or
Not sure off the top of my head - its very likely this pattern was copied from elsewhere, so good chance its not needed.

2022-09-12 01:51 UTC, natoscott approved these changes

2022-09-14 19:51 UTC, nhosoi commented
[citest]

2022-09-19 23:01 UTC, richm commented on tasks/firewall.yml
> +    - (ansible_facts['distribution'] in ['CentOS', 'RedHat'] and
I think it would be better to be exclusive here e.g.
```yaml
  when:
    - not (ansible_facts['os_family'] == 'RedHat' or
      ansible_facts['distribution_version'] is version('7', '<'))
```
and below too

You'll also need to update the README documentation for `metrics_manage_firewall` - something like "firewall management not supported on EL6"

2022-09-19 23:23 UTC, richm commented on README.md
> +Please note that configuring firewalld is ensured regardless of the
Not sure what you mean here

2022-09-19 23:30 UTC, richm commented on tasks/selinux.yml
> +        selinux_booleans: "{{ __metrics_selinux }}"
In general, avoid using `set_fact` because it "pollutes" the global variable namespace.  However, there are cases where it is better to use `set_fact` - e.g. above, where you have to dynamically construct `__metrics_firewall` - that would be really difficult to do with just jinja filters - you could probably do that with a `{% .... %}` block of jinja code also.

2022-09-20 00:31 UTC, nhosoi commented on tasks/firewall.yml
> +    - (ansible_facts['distribution'] in ['CentOS', 'RedHat'] and
> I think it would be better to be exclusive here e.g.
> 
> ```yaml
>   when:
>     - not (ansible_facts['os_family'] == 'RedHat' or
>       ansible_facts['distribution_version'] is version('7', '<'))
> ```

You are not suggesting to replace the line 44 - 46 with this condition, right? it's rather opposite...
```
    - not (ansible_facts['os_family'] == 'RedHat' or
      ansible_facts['distribution_version'] is version('7', '<'))
```
So, will it be something like this? (I thought version 7 is not really for fedora, but it does not do much harm...)
```
    - ansible_facts['os_family'] == 'RedHat'
    - ansible_facts['distribution_version'] is version('7', '>=')
```
(I might have misunderstood completely...)
> and below too
> 
> You'll also need to update the README documentation for `metrics_manage_firewall` - something like "firewall management not supported on EL6"

+1 Thanks!

2022-09-20 00:41 UTC, nhosoi commented on tasks/selinux.yml
> +        selinux_booleans: "{{ __metrics_selinux }}"
> hmm - this means the metrics role will _always manage selinux_, _even if `metrics_manage_selinux: false`_?

In the current implementation, `metrics_manage_selinux: false` means removing the selinux port. I wanted to have a cleaning up option, and the value `false` is used for that. The other roles, ha_cluster, vpn, logging, and postfix share the same definition. Please note that it's the same for `metrics_manage_firewall`. It's managed, by default. And if it's set to false, the configuration is dropped.

2022-09-20 03:56 UTC, nhosoi commented on README.md
> +Please note that configuring firewalld is ensured regardless of the
Sorry, it's not clear at all... :p I wanted to say `firewalld` package is always installed regardless of the `metrics_manage_firewall` value. If the value is true, the ports are enabled. If the value is false, the ports are disabled.

2022-09-20 03:58 UTC, nhosoi commented
[citest]

2022-09-20 14:05 UTC, richm commented on tasks/firewall.yml
> +    - (ansible_facts['distribution'] in ['CentOS', 'RedHat'] and
I think the condition should be "use the firewall role if not using a Red Hat family OS, or if the version is > 6" - that way, if not using Red Hat, CentOS, Fedora, we use the firewall role, or if the version is > 6.  And yes, this works for Fedora because the version numbers for Fedora are so much greater than the EL versions.

On second thought - maybe it would be better to have an inclusive version - that will force us to revisit this if/when the firewall role supports other platforms:
```yaml
    - ansible_facts['os_family'] == 'RedHat'
    - ansible_facts['distribution_version'] is version('7', '>=')
```

2022-09-20 20:30 UTC, nhosoi commented
Hi @richm, @natoscott,

I'm fixing README.md that I missed to update...  Could you please take a look at this commit?
https://github.com/linux-system-roles/metrics/pull/126/commits/8f3b41aa2b6b2c2008f70776de2512005717a9ea
Thanks!

2022-09-22 18:16 UTC, richm commented on README.md
> +roles directly.
```suggestion
role directly.
```

2022-09-22 18:16 UTC, richm commented on README.md
> +roles directly.
```suggestion
role directly.
```

2022-09-22 18:18 UTC, richm commented on tasks/selinux.yml
>      - name: Set pcp_bind_all_unreserved_ports
```suggestion
# SPDX-License-Identifier: MIT
---
- name: Ensure the port status with the selinux role
  include_role:
    name: fedora.linux_system_roles.selinux
  vars:
    selinux_booleans:
      - [{name: 'pcp_bind_all_unreserved_ports', state: 'on'}]
  when:
    - metrics_manage_selinux | bool
```

2022-09-23 18:43 UTC, richm commented
[citest]

2022-09-26 16:42 UTC, nhosoi commented
[citest bad]

2022-09-26 18:20 UTC, richm commented on README.md
> +ansible-galaxy collection install -r meta/requirements.yml
```suggestion
ansible-galaxy collection install -r meta/collection-requirements.yml
```

2022-09-27 17:14 UTC, nhosoi commented
Note: need to wait for the new 9.2 compose for the 9.2 CI failures.
(See https://github.com/linux-system-roles/metrics/pull/125#issuecomment-1259375366)

2022-09-30 13:09 UTC, richm commented
[citest]

2022-10-10 15:43 UTC, nhosoi commented
@natoscott, @richm, @andreasgerstmayr, thank you for your reviews and helps.
As all the CI tests passed, I'm merging this pr.

2022-10-10 15:43 UTC, merged

2022-10-10 21:19 UTC, natoscott commented
@nhosoi perfect, thanks Noriko!