Clarify requirements on RHEL managed hosts
linux-system-roles/metrics pull request #20
Opened 2020-08-20 09:13 UTC by pcahyna

2020-08-20 11:58 UTC, kurik approved these changes
Thanks Pavel. Looks good to me.

2020-08-20 22:51 UTC, natoscott requested changes

2020-08-20 22:51 UTC, natoscott commented on README.md
> +earlier versions you may enable EPEL repositories as a workaround, but
@pcahyna looks good.  I would drop the bracketed sentence though - Grafana doesn't exist even in EPEL, and the version of Redis in both EPEL6 and EPEL7 is too old for our needs.

2020-08-20 22:51 UTC, natoscott commented on README.md
> +On RHEL 7 and RHEL 6 it is needed to have the Optional repository
So I'd also drop this last sentence - its misleading - we should just assert RHEL8 (and Fedora) are the best sources of up-to-date, working packages for the graphing and scalable querying options.

2020-08-20 22:57 UTC, pcahyna commented on README.md
> +earlier versions you may enable EPEL repositories as a workaround, but
ok

2020-08-20 23:00 UTC, pcahyna commented on README.md
> +On RHEL 7 and RHEL 6 it is needed to have the Optional repository
The last sentence does not relate to graphing and scalable querying options. Optional is needed for the basic functionality. #17 was not sufficient, there are other packages available only in Optional (I think `pcp-pmda-dm`).

2020-08-24 00:52 UTC, natoscott commented on README.md
> +On RHEL 7 and RHEL 6 it is needed to have the Optional repository
@pcahyna Ah, I see what you mean - that final sentence looks good as-is then.

2020-08-24 00:55 UTC, natoscott commented on README.md
> +earlier versions you may enable EPEL repositories as a workaround, but
@richm Centos is in the same broader category as RHEL - we could perhaps use words like "... on Fedora, CentOS8, and RHEL8"  (explicitly recommending el8 only in both cases, whereas any supported Fedora is fine)

2020-08-24 10:26 UTC, merged